- defaults:
    link:
      create: true
      # force: true
      relink: true

- clean:
  - '~'
  - ~/.config

- link:
    ~/.atom:
    ~/.config/fish:
    ~/.config/git:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.bin/git-open: git-open/git-open
    ~/.hyper.js:
    ~/.ssh/config: ssh/config
    ~/.tmux.conf:

- shell:
  - [git submodule update --init --recursive, Installing git submodules]
  # TODO: handle local or system specific Homebrew packages
  # - [brew bundle, Install Homebrew packages]
  # - [apm install --packages-file=atom/packages.list --compatible --production, Installing Atom packages]
  # - [apm clean, Remove unspecifed Atom packages]
  # - [fish_update_completions, Update fish autocompletions]
