##### TASKS #####

[tasks.default__macos]
  deps = [
    "common",
  ]
  links = [
  ]

[tasks.default__debian]

[tasks.personal__macos]

[tasks.personal__debian]

[tasks.work__macos]

[tasks.work__debian]
  
[tasks.common]
  deps = [
    "fish",
    "fish-config",
    "fisherman",
    "git",
    "homebrew",
  ]

################################################################################

[tasks.aws__macos]
  cmds = [
    ["@install", "awscli"],
  ]
  
  links = [
    [".aws/config", "conf/tools/aws/config"],
  ]
  
  cmdspost = [
    ["chmod", "600", "${HM_DEST}/.aws/config"],
  ]

[tasks.git]
  deps = [
    "common",
  ]
  
  rejects = [
    ["which", "git"],
  ]
  cmds = [
    ["@install", "git"],
  ]
  
[tasks.git-config]
  deps = [
    "git",
  ]
  
  cmds = [
    ["mkdir", "-p", "$HOME/.config/git"],
  ]
  
  links = [
    [".gitconfig", "conf/tools/git/gitconfig"],
    [".config/git/gitignore", "conf/tools/git/gitignore"],
    [".config/git/templates", "conf/tools/git/templates"],
    # [".config/git/gitattributes", "conf/tools/git/gitattributes"],
  ]

[tasks.ssh]
  deps = [
    "common",
  ]
  
  cmds = [
    ["@install", "openssh"],
  ]

  links = [
    [".ssh/config", "conf/tools/ssh/config"],
  ]

[tasks.homebrew]
  cmds = [
    ["echo", "Installing Homebrew"],
    ['ruby', '-e', '"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'],
    ["echo", "Updating Homebrew"],
    ["brew", "update"],
  ]

[tasks.fish]
  rejects = [
    ["which", "fish"],
    ['test', '"$SHELL"', '=', '"/usr/local/bin/fish"'],
  ]
  
  cmds = [
    ["@install", "fish"],
    ["sudo", "chsh", "-s", "/usr/local/bin/fish", "$USER"],
  ]
  
[tasks.fish-config]
  deps = [
    'fish',
  ]
  
  links = [
    [".config/fish/config.fish", "conf/shell/fish/config.fish"],
    [".config/fish/conf.d", "conf/shell/fish/conf.d"],
    [".config/fish/functions", "conf/shell/fish/functions"],
  ]

[tasks.fisherman]
  deps = [
    "fish",
  ]
  
  cmds = [
    ["curl", "-Lo", "$HOME/.config/fish/functions/fisher.fish", "--create-dirs", "https://git.io/fisher"],
  ]
  
[tasks.hyper__macos]
  deps = [
    "common",
  ]
  
  cmds = [
    ["@cask", "hyper"],
  ]
  
  links = [
    [".hyper.js", "conf/terminal/hyper.js"],
  ]

[tasks.hpm]
  deps = [
    "hyper",
    "node",
  ]
  
  cmds = [
    ["npm", "install", "--global", "hpm-cli"],
  ]
  
[tasks.hyper-plugins]
  deps = [
    "hpm",
  ]
  
  cmds = [
    ["hpm", "install", "hypercwd"],
    ["hpm", "install", "hyper-statusline"],
  ]

[tasks.node]
  deps = [
    "nvm",
  ]
  
  cmds = [
    ["@fish", "nvm install --lts"],
    ["@npm-install", "npm"],
  ]
  
  links = [
    [".npmrc", "conf/languages/javascript/npmrc"],
  ]

[tasks.nvm]
  deps = [
    "common",
  ]
  
  envs = [
    ["NVM_DIR", "$HOME/.nvm"],
    ["NVM_BIN", "/usr/local/opt/nvm/nvm.sh"],
  ]
  
  cmds = [
    ["@install", "nvm"],
    ["mkdir", "-p", "$NVM_DIR"],
    ["ln", "-sf", "$NVM_BIN", "$NVM_DIR/nvm.sh"],
    ["@fish", "fisher nvm"],
  ]
  
[tasks.php]
  deps = ["common"]
  templates = [
    ["test"]
  ]

[tasks.vim]
  cmds = [
    ["rm", "-rf", "${HM_DEST}/.config/vim"],
  ]
  links = [
    [".config/vim", "conf/editors/vim/config"],
    [".config/vim/.vimrc", "conf/editors/vim/vimrc"],
    [".config/vim/.vim", "conf/editors/vim/vim"],
  ]
  
[tasks.shopify]
  cmds = [
    ["@install", "themekit"],
    ["@npm-install", "slate-cli"],
  ]

##### MACROS #####

[macros.install__macos]
  deps = [
    "homebrew",
  ]
  
  prefix = ["brew", "install"]

[macros.install__debian]
  prefix = ["sudo", "apt-get", "install", "-y"]

[macros.cask__macos]
  deps = [
    "homebrew",
  ]
  
  prefix = ["brew", "cask", "install"]
  
[macros.npm-install]
  deps = [
    "node",
  ]
  
  prefix = ["npm", "install", "--global"]

[macros.fish]
  prefix = ["/usr/local/bin/fish", "-c"]


