- defaults:
    link:
      create: true
      force: true
      relink: true

- clean:
  - '~'

- link:
    ~/.atom:
    ~/.config/fish: config/fish
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore:
    # ~/.ssh/config:

- shell:
  - [git submodule update --init --recursive, Installing git submodules]
  # TODO: handle local or system specific Homebrew packages
  # - [brew bundle, Install Homebrew packages]
  # - [apm install --packages-file=atom/packages.list --compatible --production, Installing Atom packages]
  # - [apm clean, Remove unspecifed Atom packages]
