#!/usr/bin/env zsh
# shellcheck shell=bash

PRAGMA_HEADER="Pragma: akamai-x-cache-on, akamai-x-cache-remote-on, akamai-x-check-cacheable, akamai-x-get-cache-key, akamai-x-get-true-cache-key"
PRAGMA_AUTH_HEADER="PragmaAuth: ${AKAMAI_PRAGMA_AUTH_TOKEN}"

if [[ -z "$1" ]]; then
  echo "A URL arg is required" && return 1
fi

curl -I -H "$PRAGMA_HEADER" -H "$PRAGMA_AUTH_HEADER" "$1"
