#!/bin/zsh
# shellcheck shell=bash

  local cmd

  case "$1" in
    enable)
      cmd="load"
      ;;
    disable)
      cmd="unload"
      ;;
    *)
      echo "error: unknown argument '$1'"
      exit 1
      ;;
  esac

  sudo launchctl $cmd /Library/LaunchDaemons/com.zscaler.tunnel.plist
  sudo launchctl $cmd /Library/LaunchAgents/com.zscaler.tray.plist
