#!/usr/bin/env bash

VS_CODE_CONFIG_DIR="${HOME}/.config/vscode"
VS_CODE_USER_DIR="${HOME}/Library/Application Support/Code/User"

if [ -d "$VS_CODE_USER_DIR" ]; then
  ln -snF "${VS_CODE_CONFIG_DIR}/settings.json" "${VS_CODE_USER_DIR}/settings.json"
  ln -snF "${VS_CODE_CONFIG_DIR}/keybindings.json" "${VS_CODE_USER_DIR}/keybindings.json"
  ln -snF "${VS_CODE_CONFIG_DIR}/snippets" "${VS_CODE_USER_DIR}/snippets"
fi
