tap 'cloudflare/cloudflare'
tap 'dart-lang/dart'
tap 'thoughtbot/formulae'

cask 'appzapper'
cask 'cloudflare-warp'
cask 'google-chrome'
cask 'kindlegen'
cask 'yubico-yubikey-manager'
cask 'yubico-yubikey-personalization-gui'
cask 'yubico-yubikey-piv-manager'

mas 'DaisyDisk', id: 411643860
mas 'Kindle', id: 405399194
mas 'Logic Pro X', id: 634148309
mas 'Paprika Recipe Manager', id: 451907568
mas 'Transmit', id: 403388562
